whish_list/config/routes.rb
Rails.application.routes.draw do
  resources :product_personal_whish_lists do
    collection do
      get "product_search" => "product_personal_whish_lists#product_search", as: :product_search
      get "get_categories" => "product_personal_whish_lists#get_categories", as: :get_categories
      get "get_product_by_category/:id" => "product_personal_whish_lists#get_product_by_category", as: :get_product_by_category
    end
  end
  resources :personal_whish_lists, path: ""

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

whish_list/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

whish_list/app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent, :class_name => "Category", :foreign_key => "parent_id"

  has_many :childrens, class_name: "Category", foreign_key: "parent_id", dependent: :destroy

  has_many :products, class_name: "product", foreign_key: "reference_id"

  def self.get_category_tree_ids(category_id, ids)
    ids.push(category_id)

    begin
      category = Category.find(category_id)
    rescue ActiveRecord::RecordNotFound => e
      category = nil
    end
    if (category)
      category.childrens.each do |child|
        ids.push(get_category_tree_ids(child.id, ids))
      end
    end
    return ids
  end
end

whish_list/app/models/personal_whish_list.rb
class PersonalWhishList < ApplicationRecord
    has_many :product_personal_whish_lists
    has_many :products, through: :product_personal_whish_lists
end

whish_list/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  paginates_per 12

  def self.get_by_category(category_id)
    categories = Category.get_category_tree_ids(category_id, [])
    return Product.where(category_id: categories)
  end
end

whish_list/app/models/product_personal_whish_list.rb
class ProductPersonalWhishList < ApplicationRecord
  belongs_to :personal_whish_list, class_name: "PersonalWhishList", foreign_key: "personal_whish_list_id"
  belongs_to :product, class_name: "Product", foreign_key: "product_id"
end

whish_list/app/models/tree_view.rb
class TreeView

end

whish_list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

whish_list/app/controllers/personal_whish_lists_controller.rb
class PersonalWhishListsController < ApplicationController
  before_action :set_personal_whish_list, only: [:show, :edit, :update, :destroy]

  # GET /personal_whish_lists
  # GET /personal_whish_lists.json
  def index
    @personal_whish_lists = PersonalWhishList.all
      .joins("join product_personal_whish_lists on product_personal_whish_lists.personal_whish_list_id = personal_whish_lists.id")
      .joins("join products on products.id = product_personal_whish_lists.product_id")
      .select("personal_whish_lists.id,personal_whish_lists.name,count(product_personal_whish_lists.quantity) as total_products, sum(products.price * product_personal_whish_lists.quantity) as total_value")
  end

  # GET /personal_whish_lists/1
  # GET /personal_whish_lists/1.json
  def show
  end

  # GET /personal_whish_lists/new
  def new
    @personal_whish_list = PersonalWhishList.new
  end

  # GET /personal_whish_lists/1/edit
  def edit
  end

  # POST /personal_whish_lists
  # POST /personal_whish_lists.json
  def create
    @personal_whish_list = PersonalWhishList.new(personal_whish_list_params)

    respond_to do |format|
      if @personal_whish_list.save
        format.html { redirect_to @personal_whish_list, notice: "Personal whish list was successfully created." }
        format.json { render :show, status: :created, location: @personal_whish_list }
      else
        format.html { render :new }
        format.json { render json: @personal_whish_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_whish_lists/1
  # PATCH/PUT /personal_whish_lists/1.json
  def update
    respond_to do |format|
      if @personal_whish_list.update(personal_whish_list_params)
        format.html { redirect_to @personal_whish_list, notice: "Personal whish list was successfully updated." }
        format.json { render :show, status: :ok, location: @personal_whish_list }
      else
        format.html { render :edit }
        format.json { render json: @personal_whish_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_whish_lists/1
  # DELETE /personal_whish_lists/1.json
  def destroy
    @personal_whish_list.destroy
    respond_to do |format|
      format.html { redirect_to personal_whish_lists_url, notice: "Personal whish list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_personal_whish_list
    @personal_whish_list = PersonalWhishList.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def personal_whish_list_params
    params.require(:personal_whish_list).permit(:name)
  end
end

whish_list/app/controllers/product_personal_whish_lists_controller.rb
class ProductPersonalWhishListsController < ApplicationController
  # before_action :set_product_personal_whish_list, only: [:edit, :update, :destroy]

  # GET /product_personal_whish_lists
  # GET /product_personal_whish_lists.json
  def index
  end

  # GET /product_personal_whish_lists/1
  # GET /product_personal_whish_lists/1.json
  def show
    @personal_whish_list = PersonalWhishList.find(params[:id])
  end

  # POST /product_personal_whish_lists
  # POST /product_personal_whish_lists.json
  def create
    @product_personal_whish_list = ProductPersonalWhishList.where(product_id: params[:product_id], personal_whish_list_id: params[:personal_whish_list_id])

    if (@product_personal_whish_list && params[:quantity] == 0)
      # Deleta registro
      @product_personal_whish_list.first.destroy
      return render :json => { message: "Excluido com sucesso" }
    elsif (@product_personal_whish_list and @product_personal_whish_list.count > 0)
      # Atualiza
      if @product_personal_whish_list.update(product_personal_whish_list_params)
        return render :json => { message: "Atualizado" }
      end
    else
      # Cria novo registro
      @product_personal_whish_list = ProductPersonalWhishList.new(product_personal_whish_list_params)
      if @product_personal_whish_list.save
        return render :json => { message: "Criado com sucesso" }
      end
    end

    return render :json => { message: "Erro ao criar" }
  end

  def get_categories()
    tree = []
    categories = Category.all
    tree = generate_categories_tree(categories)
    render :json => tree
  end

  def get_product_by_category
    products = Product.get_by_category(params[:id])
    pagined_products = products.page(params[:page])
    render :json => { products: pagined_products, total_items: products.count, total_pages: pagined_products.total_pages, current_page: pagined_products.current_page }
  end

  #Metodo de busca para o produto
  def product_search()
    product = nil
    if (params[:category] != nil and params[:category].to_i > 0)
      products = Product.get_by_category(params[:category]).where("lower(name) like ?", "%#{params[:name].to_s.downcase}%")
    else
      products = Product.where("lower(name) like ?", "%#{params[:name].to_s.downcase}%")
    end
    pagined_products = products.page(params[:page])
    render :json => { products: pagined_products, total_items: products.count, total_pages: pagined_products.total_pages, current_page: pagined_products.current_page }
  end

  private

  def set_product_personal_whish_list
    @product_personal_whish_list = ProductPersonalWhishList.find(params[:id])
  end

  def product_personal_whish_list_params
    params.require(:product_personal_whish_list).permit(:product_id, :personal_whish_list_id, :quantity)
  end

  def generate_categories_tree(categories)
    tree = []

    categories.each do |category|
      tree.push(
        {
          id: category.id.to_s,
          parent: category.parent_id ? category.parent_id : "#",
          text: category.name,
          state: {
            opened: true,  # is the node open
          },
        }
      )
    end
    return tree
  end
end

whish_list/app/helpers/application_helper.rb
module ApplicationHelper
end

whish_list/app/helpers/personal_whish_lists_helper.rb
module PersonalWhishListsHelper
end

whish_list/app/helpers/product_personal_whish_lists_helper.rb
module ProductPersonalWhishListsHelper
end

whish_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Lista de Desejos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link href="/assets/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
     <link href="/assets/bootstrap/scss/bootstrap.scss" rel="stylesheet" type="text/css">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= yield :head %>
  </head>

<body id="page-top" class="sidebar-toggled">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon rotate-n-15">
       
        </div>
        <div class="sidebar-brand-text mx-3">White Label</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="/">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Dados
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Listas</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="<%= personal_whish_lists_path %>">Todas Listas</a>
            <a class="collapse-item" href="<%= new_personal_whish_list_path %>">Nova Lista</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

         <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>

            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div class="font-weight-bold">
                    <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                    <div class="small text-gray-500">Emily Fowler · 58m</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                    <div class="status-indicator"></div>
                  </div>
                  <div>
                    <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                    <div class="small text-gray-500">Jae Chun · 1d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                    <div class="status-indicator bg-warning"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                    <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                    <div class="small text-gray-500">Chicken the Dog · 2w</div>
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
          <%= yield %>
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>
  <!-- Bootstrap core JavaScript-->
  <script src="/assets/jquery/jquery.min.js"></script>
  <script src="/assets/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/assets/jquery-easing/jquery.easing.min.js"></script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= yield :end_body %>

</body>

</html>

whish_list/app/views/personal_whish_lists/_form.html.erb
<%= form_with(model: personal_whish_list, local: true) do |form| %>
  <% if personal_whish_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(personal_whish_list.errors.count, "error") %> prohibited this personal_whish_list from being saved:</h2>

      <ul>
      <% personal_whish_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

whish_list/app/views/personal_whish_lists/edit.html.erb
<h1>Editando Personal Whish List</h1>

<%= render 'form', personal_whish_list: @personal_whish_list %>

<%= link_to 'Ver', @personal_whish_list %> |
<%= link_to 'Voltar', personal_whish_lists_path %>

whish_list/app/views/personal_whish_lists/index.html.erb
<% content_for :head do %>
	<link href="assets/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
<% end %>

<p id="notice"><%= notice %></p>

 <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h3 class="m-0 font-weight-bold text-primary">Minhas Listas</h3>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
    <tr>
      <th>Nome</th>
      <th>Total Itens</th>
      <th>Valor Total</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @personal_whish_lists.each do |personal_whish_list| %>
      <tr>
        <td><%= personal_whish_list.name %></td>
        <td><%= personal_whish_list.total_products %></td>
        <td><%= number_to_currency(personal_whish_list.total_value, unit: "R$ ", separator: ",", delimiter: "") %></td>
        <td>
        <a class="mr-3" data-toggle="tooltip" data-placement="top" title="Editar Lista" href="<%=product_personal_whish_list_path(personal_whish_list.id)%>"> <i class="fas fa-clipboard-list"></i></a>
        <a class="mr-3" data-toggle="tooltip" data-placement="top" title="Editar dados da lista" href="<%=edit_personal_whish_list_path(personal_whish_list)%>"><i class="fas fa-edit"></i></a>
        <%= link_to(personal_whish_list, method: :delete, data: { confirm: 'Tem certeza que deseja deletar?' }) do %><i class="fas fa-trash-alt"></i> <%end%></td>
      </tr>
    <% end %>
        </tbody>
                </table>
              </div>
            </div>
          </div>

<br>

<% content_for :end_body do %>
  <script src="assets/datatables/jquery.dataTables.min.js"></script>
  <script src="assets/datatables/dataTables.bootstrap4.min.js"></script>
<% end %>
  

whish_list/app/views/personal_whish_lists/new.html.erb
<h1>New Personal Whish List</h1>

<%= render 'form', personal_whish_list: @personal_whish_list %>

<%= link_to 'Back', personal_whish_lists_path %>

whish_list/app/views/personal_whish_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @personal_whish_list.name %>
</p>

<%= link_to 'Edit', edit_personal_whish_list_path(@personal_whish_list) %> |
<%= link_to 'Back', personal_whish_lists_path %>

whish_list/app/views/product_personal_whish_lists/show.html.erb
<% content_for :head do %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />
<% end %>

<p id="notice">
    <%= notice %>
</p>

<h2>Minha lista personalizada -
    <%= @personal_whish_list.name %>
</h2>

<div id="app">
<%= hidden_field_tag('personal_whish_list_id', @personal_whish_list.id) %>
    <!-- Page Content -->
    <div class=container-fluid>

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h5 class="my-2">Categorias </h5>
            </div>
            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample">
                <div class="card-body">
                    <div id="category-tree"></div>
                </div>
            </div>
        </div>

    <%= render :partial => 'products/index'%>

    <card-products v-bind:category_selected="categorySelected" v-bind:products="products">
    <card-products>

    <div v-show="products && products.length > 0" class="row justify-content-center">
        <paginate :page-count="pagination.totalPages" :page-range="pagination.pageRarge" :click-handler="clickCallback" :prev-text="'Anterior'" :next-text="'Próximo'" :container-class="'pagination'" :page-class="'page-link'">
        </paginate>
    </div>

</div>

                
<% content_for :end_body do %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="https://unpkg.com/vuejs-paginate@0.9.0"></script>
  <%= javascript_include_tag "product_personal_whish_lists" %>

<% end %>

whish_list/app/views/products/_index.html.erb
<!-- Page Heading -->

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h5 class="my-2">Produtos
            <small v-if="categorySelected !== undefined">{{categorySelected.text}}</small>
        </h5>

    </div>
    <div class="card-body">
        <div class="row justify-content-end mb-3">
            <div class="input-group col-xl-6 col-lg-6 col-md-4 col-sm-5 col-11">
            
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1"><i class="fas fa-search"></i></span>
                        </div>
                        <input v-model="productNameSearch" type="text" class="form-control" placeholder="">
                    </div>
            </div>
        </div>


        <div class="row">

            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 mb-4 custom-selected" v-for="(product, index) in products">
                
                    <div class="card h-100">
                        <img class="card-img-top" src="http://placehold.it/700x400" alt="">
                        <div class="card-body">
                            <h4 class="card-title">
                                {{product.name}}
                            </h4>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                            <p class="card-text">R$ {{ formatPrice(product.price) }}</p>
                            <div></div>
                            <div class="row">
                                <div class="col-4"><button class="btn-circle" v-on:click="addItemList(product,index)">+</button></div>
                                <div class="col-4 text-center ">{{product.quantity}}</div>
                                <div class="col-4"><button class="btn-circle" v-on:click="removeItemList(product,index)">-</button></div>
                            </div>
                        </div>
                    </div>
                
            </div>

        </div>
    </div>
</div>



<!-- /.row -->

<% content_for :end_body do %>
    <script>
        Vue.component('card-products', {
            props: ['category_selected', 'products'],
            methods: {

            },

        })
    </script>

    <% end %>